// AUTH
export const GOT_USER_INFO = "GOT_USER_INFO";

// SIGN UP
// export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
// export const SIGNUP_ERROR = "SIGNUP_ERROR";


// SIGN IN
// export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
// export const SIGNIN_ERROR = "SIGNIN_ERROR";


// SIGN OUT
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
// export const SIGNOUT_ERROR = "SIGNOUT_ERROR";


// Editor
export const EDITOR_PREVIEW = "EDITOR_PREVIEW";
export const EDITOR_SAVE = "EDITOR_SAVE";
export const EDITOR_UPLOAD_ERROR = "EDITOR_UPLOAD_ERROR";
export const EDITOR_UPLOAD_SUCCESS = "EDITOR_UPLOAD_SUCCESS";
export const EDITOR_UPLOAD_IMAGE_SUCCESS = "EDITOR_UPLOAD_IMAGE_SUCCESS";

// folder
export const GET_FOLDER_LIST = "GET_FOLDER_LIST";
export const FOLDER_ERROR = "FOLDER_ERROR";

// error
export const GENERAL_ERROR = "GENERAL_ERROR";


// article
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";


export const TEST_TEST = "TEST_TEST";

